services:
- docker

addons:
  apt:
    packages:
    - expect
    - rpm
    - dpkg-sig
    - gnupg

git:
    submodules: false
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive --remote
    - pip install awscli --upgrade --user
    - gem install package_cloud
    - echo "{\"url\":\"https://packagecloud.io\",\"token\":\"${PKGCLD_WRITE_TOKEN}\"}" > ~/.packagecloud

before_script:
- source packaging/scripts/travis-helpers.sh
- export -f travis_nanoseconds
- export -f travis_fold
- export -f travis_time_start
- export -f travis_time_finish

script:
- script_block 'build' 'bash scripts/travis-build.sh build'
- script_block 'sign' 'bash scripts/travis-build.sh sign'
- script_block 'test' 'bash scripts/travis-build.sh test'
- script_block 'publish' 'bash scripts/travis-build.sh publish'

notifications:
  slack:
    secure: ep3APeVD6QwEkTJ8YR0f1eDzcFJ2uLUIci4Aob/5ILm+v8h0hOTAe1yFoKv+iR/4PCeZ+5PvVezOMHSkFNX7rCj06Mj/ivlnng569JLjOQAR0q25aeIH+wy4oDE33HaNbNOYLMe7bXDP4SelRi9SbRRe84j6OjDgZzyDC36cyAk=HYLk2EpEdeRFD79JUOvi8cAFkMNjyGDSuA4Gv8MiwoKAbztAg12e6hF/QUYSnLfOrF2lyCGaxz9KrR90lOqzW3+3OHZVyu0+yZoNyl1IZ9bnZD69rMbT+AHczOV0R5gDpWVSkXkdv0AV4bGBVWqY7mmv7RIOGFoBWMdAr+f9Jn2ueiSfJnXoNThC52MVGZE9qIQvwab6BNZhzcQ6uh6ud5LfYrct34vFavuO4pgIKHzS9sBj9BgFcfsad1C+Qm1KV9DkEQ5Qvv2nwgm+JhQw1hBqX9BSVoCtfAUQjDHiHEKgPV+CJX1An1MyLQV+2s+TZ7T+2JgnPVqq9Pd+sdfOJ8wOgTaEV6Miq/NQ9mMFrDSqw3YUPw2G/LHSDF9MslkIAhJ3QFG+9iA1j44lafVZ6pJOk51UQP0vQLoxu00sXlW6Uy95yqOowpCZQP9DYfKDuoSYIPrdq7YSTEdiFaYYp971FRNVxQ1QbdYIZ7YJL7wvkqP2lngCSm3kgb5QmkgEmWF7iy1qf2JGAAvVav/gKFjY/XQ=