install: false

git:
    submodules: false
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
    - pip install awscli --upgrade --user

script:
- bash scripts/travis_build.sh build
- bash scripts/travis_build.sh publish